/** KFE Admin source-record form definitions. Derived values are never entered here. */
const text=(key,label,options={})=>({key,label,type:'text',...options});
const number=(key,label,options={})=>({key,label,type:'number',...options});
const date=(key,label,options={})=>({key,label,type:'date',...options});
const select=(key,label,options=[],extra={})=>({key,label,type:'select',options,...extra});
const checkbox=(key,label,options={})=>({key,label,type:'checkbox',...options});
const textarea=(key,label,options={})=>({key,label,type:'textarea',...options});

export const ADMIN_FORM_DEFINITIONS={
 vehicle:{key:'vehicle',title:'Vehicle',category:'operations',fields:[text('registrationNumber','Registration number',{required:true}),text('make','Make',{required:true}),text('model','Model',{required:true}),text('variant','Variant'),date('acquiredOn','Acquisition date',{required:true}),number('acquisitionValue','Acquisition cost/value',{min:0}),number('openingOdometerKm','Opening odometer (km)',{required:true,min:0}),select('fuelType','Fuel type',['CNG','Petrol','Diesel','Electric','Hybrid'],{required:true}),number('tankCapacity','Tank / battery capacity',{min:0}),select('status','Vehicle status',['Active','Inactive','Sold'],{required:true}),date('statusDate','Status date'),date('expiryDate','Expiry date'),number('sellPrice','Sell price',{min:0}),date('saleDate','Sale date'),checkbox('active','Active',{defaultValue:true}),textarea('notes','Notes')]},
 driver:{key:'driver',title:'Driver',category:'operations',fields:[text('name','Full name',{required:true}),text('phone','Phone number'),text('licenseNumber','Driving licence number'),date('licenseExpiry','Licence expiry'),date('joinedOn','Joined on'),select('status','Status',['Active','Inactive','Suspended'],{required:true}),select('vehicleId','Assigned vehicle',[]),textarea('notes','Notes')]},
 compliance:{key:'compliance',title:'Compliance',category:'operations',fields:[select('vehicleId','Vehicle',[],{required:true}),select('complianceType','Compliance type',['Insurance','PUC','Permit','Fitness','Tax','Other'],{required:true}),text('referenceNumber','Reference number'),date('validFrom','Valid from',{required:true}),date('validUntil','Valid until',{required:true}),number('cost','Amount',{min:0}),textarea('notes','Notes')]},
 maintenance:{key:'maintenance',title:'Maintenance',category:'operations',fields:[select('vehicleId','Vehicle',[],{required:true}),date('performedOn','Maintenance date',{required:true}),select('maintenanceType','Maintenance type/category',['Service','Repair','Tyres','Battery','Other'],{required:true}),number('odometerKm','Odometer (km)',{min:0}),select('validityType','Validity type',['None','KM based','Duration based'],{defaultValue:'None'}),number('validityValue','Validity value',{min:0}),number('cost','Amount',{required:true,min:0}),text('vendor','Vendor'),date('nextServiceDate','Next service date'),number('nextServiceKm','Next service KM',{min:0}),textarea('description','Description'),textarea('notes','Notes')]},
 driverCollectedData:{key:'driverCollectedData',title:'Driver-collected Data',category:'operations',calculationRole:'supporting-only',fields:[select('driverId','Driver',[],{required:true}),select('vehicleId','Vehicle',[],{required:true}),date('recordedOn','Recorded on',{required:true}),number('startOdometerKm','Start odometer (km)',{min:0}),number('endOdometerKm','End odometer (km)',{min:0}),number('cashCollected','Cash collected',{min:0}),number('otherCollectedAmount','Other collected amount',{min:0}),textarea('notes','Notes')]},
 loan:{key:'loan',title:'Loan',category:'finance',calculationRole:'authoritative',fields:[text('lender','Lender',{required:true}),text('accountReference','Account reference'),number('principal','Principal',{required:true,min:0}),number('annualInterestRate','Annual interest rate (%)',{required:true,min:0}),number('tenureMonths','Tenure (months)',{required:true,min:1}),date('startDate','Loan start date',{required:true}),select('status','Loan status',['Active','Closed','Settled'],{required:true}),textarea('notes','Notes')]},
 loanPayment:{key:'loanPayment',title:'Loan Payments',category:'finance',calculationRole:'authoritative-payment-record',fields:[select('loanId','Loan',[],{required:true}),number('emiNumber','EMI number',{min:1}),date('dueDate','Due date'),number('scheduledAmount','Scheduled EMI amount',{min:0}),date('paidOn','Actual payment date',{required:true}),number('amount','Actual amount paid',{required:true,min:0}),number('principalComponent','Principal component',{min:0}),number('interestComponent','Interest component',{min:0}),number('charges','Delayed payment amount/charges',{min:0}),select('status','Payment status',['Paid','Partial','Delayed','Reversed'],{required:true}),textarea('notes','Notes')]},
 prepayment:{key:'prepayment',title:'Prepayments',category:'finance',calculationRole:'authoritative-prepayment-record',fields:[select('loanId','Loan',[],{required:true}),date('paidOn','Prepayment date',{required:true}),number('amount','Prepayment amount',{required:true,min:0}),number('outstandingBefore','Outstanding principal before prepayment',{min:0}),number('outstandingAfter','Outstanding principal after prepayment',{min:0}),select('effect','Effect on loan schedule',['Reduce tenure','Reduce EMI','No schedule change'],{required:true}),select('status','Prepayment status',['Planned','Applied','Reversed'],{required:true}),textarea('reason','Reason'),textarea('notes','Notes')]},
 driverTarget:{key:'driverTarget',title:'Driver Target',category:'targetBreakEven',calculationRole:'authoritative',fields:[select('driverId','Driver',[],{required:true}),date('effectiveFrom','Effective from',{required:true}),date('effectiveUntil','Effective until'),number('targetRevenue','Desired driver profit / take-home',{min:0}),number('targetHours','Target hours',{min:0}),number('targetKm','Target kilometres',{min:0}),checkbox('active','Active',{defaultValue:true}),textarea('notes','Notes')]},
 breakEvenInputs:{key:'breakEvenInputs',title:'Break-even Inputs',category:'targetBreakEven',calculationRole:'authoritative-inputs',fields:[date('effectiveFrom','Effective from',{required:true}),number('maintenanceProvisionPerKm','Maintenance provision per vehicle km',{min:0,defaultValue:2}),textarea('notes','Notes')]}
};
export const ADMIN_FORM_KEYS=Object.keys(ADMIN_FORM_DEFINITIONS);
export function getAdminFormDefinition(formKey){return ADMIN_FORM_DEFINITIONS[formKey]??null;}
