/** KFE Admin source-record form definitions. Operational Work/Timeline entries are intentionally not Admin forms. Derived values are never entered here. */
const text=(key,label,options={})=>({key,label,type:'text',...options});
const number=(key,label,options={})=>({key,label,type:'number',...options});
const date=(key,label,options={})=>({key,label,type:'date',...options});
const select=(key,label,options=[],extra={})=>({key,label,type:'select',options,...extra});
const checkbox=(key,label,options={})=>({key,label,type:'checkbox',...options});
const textarea=(key,label,options={})=>({key,label,type:'textarea',...options});

export const ADMIN_FORM_DEFINITIONS={
 vehicle:{key:'vehicle',title:'Vehicle',createLabel:'Vehicle',category:'businessSetup',fields:[text('registrationNumber','Registration number',{required:true}),text('make','Make',{required:true}),text('model','Model',{required:true}),text('variant','Variant'),date('acquiredOn','Acquisition date',{required:true}),number('acquisitionValue','Acquisition cost/value',{min:0}),number('openingOdometerKm','Opening odometer (km)',{required:true,min:0}),select('fuelType','Fuel type',['CNG','Petrol','Diesel','Electric','Hybrid'],{required:true}),number('tankCapacity','Tank / battery capacity',{min:0}),select('status','Vehicle status',['Active','Inactive','Sold'],{required:true}),date('statusDate','Status date'),date('expiryDate','Expiry date'),number('sellPrice','Sell price',{min:0}),date('saleDate','Sale date'),checkbox('active','Active',{defaultValue:true}),textarea('notes','Notes')]},
 driver:{key:'driver',title:'Driver',createLabel:'Driver',category:'businessSetup',fields:[text('name','Full name',{required:true}),text('phone','Phone number'),text('licenseNumber','Driving licence number'),date('licenseExpiry','Licence expiry'),date('joinedOn','Joined on'),select('status','Status',['Active','Inactive','Suspended'],{required:true}),select('vehicleId','Assigned vehicle',[]),textarea('notes','Notes')]},
 compliance:{key:'compliance',title:'Compliance',createLabel:'Compliance Record',category:'vehicleRecords',fields:[select('vehicleId','Vehicle',[],{required:true}),select('complianceType','Compliance type',['Insurance','PUC','Permit','Road Tax','Authorization','Fitness','Tax','Other'],{required:true}),text('referenceNumber','Reference number'),date('validFrom','Valid from',{required:true}),date('validUntil','Valid until',{required:true}),number('cost','Amount',{min:0}),textarea('notes','Notes')]},
 maintenance:{key:'maintenance',title:'Maintenance',createLabel:'Maintenance Record',category:'vehicleRecords',fields:[select('vehicleId','Vehicle',[],{required:true}),date('performedOn','Maintenance date',{required:true}),select('maintenanceType','Maintenance type/category',['Service','Repair','Tyres','Battery','Other'],{required:true}),number('odometerKm','Odometer (km)',{min:0}),select('validityType','Validity type',['None','KM based','Duration based'],{defaultValue:'None'}),number('validityValue','Validity value',{min:0}),number('cost','Amount',{required:true,min:0}),text('vendor','Vendor'),date('nextServiceDate','Next service date'),number('nextServiceKm','Next service KM',{min:0}),textarea('description','Description'),textarea('notes','Notes')]},
 loan:{key:'loan',title:'Loan',collectionTitle:'Loans',createLabel:'Loan',category:'finance',calculationRole:'authoritative',fields:[text('lender','Lender',{required:true}),text('accountReference','Account reference'),number('principal','Loan amount',{required:true,min:0,exclusiveMin:true}),number('tenureMonths','Tenure (months)',{required:true,min:1}),date('startDate','Loan start date',{required:true}),number('annualInterestRatePercent','Annual interest rate (%)',{required:true,min:0}),select('status','Loan status',['Active','Closed','Settled'],{required:true}),textarea('notes','Notes')]},
 loanPayment:{key:'loanPayment',title:'Loan Payments',createLabel:'Loan Payment',category:'finance',calculationRole:'authoritative-payment-record',fields:[select('loanId','Loan',[],{required:true}),date('paidOn','Actual payment date',{required:true}),number('amount','Actual amount paid',{required:true,min:0,exclusiveMin:true}),textarea('notes','Notes')]},
 prepayment:{key:'prepayment',title:'Prepayments',createLabel:'Prepayment',category:'finance',calculationRole:'authoritative-prepayment-record',fields:[select('loanId','Loan',[],{required:true}),date('paidOn','Prepayment date',{required:true}),number('amount','Actual prepayment amount',{required:true,min:0,exclusiveMin:true}),textarea('reason','Reason'),textarea('notes','Notes')]},
 settlement:{key:'settlement',title:'Payments',collectionTitle:'Payments',createLabel:'Payment',category:'finance',calculationRole:'authoritative-settlement-record',fields:[select('settlementType','Settlement type',['Payment'],{required:true,defaultValue:'Payment'}),select('sourceType','Paying for',['Maintenance','Compliance'],{required:true}),text('sourceId','Source record ID',{required:true}),date('settledOn','Payment date',{required:true}),number('amount','Amount paid',{required:true,min:0,exclusiveMin:true}),select('paymentMethod','Payment method',['Cash','Bank transfer','UPI','Card','Cheque','Other']),text('referenceNumber','Payment reference'),textarea('notes','Notes')]},
 driverTarget:{key:'driverTarget',title:'Driver Target',createLabel:'Driver Target',category:'planningControls',calculationRole:'authoritative',fields:[select('driverId','Driver',[],{required:true}),date('effectiveFrom','Effective from',{required:true}),date('effectiveUntil','Effective until'),number('desiredDriverProfit','Desired driver profit / take-home',{required:true,min:0}),number('targetHours','Target hours',{min:0}),number('targetKm','Target kilometres',{min:0}),checkbox('active','Active',{defaultValue:true}),textarea('notes','Notes')]},
 breakEvenInputs:{key:'breakEvenInputs',title:'Break-even Inputs',createLabel:'Break-even Input',category:'planningControls',calculationRole:'authoritative-inputs',fields:[date('effectiveFrom','Effective from',{required:true}),date('effectiveUntil','Effective until'),number('maintenanceProvisionPerKm','Maintenance provision per vehicle km',{required:true,min:0,defaultValue:2}),textarea('notes','Notes')]}
};
export const ADMIN_FORM_KEYS=Object.keys(ADMIN_FORM_DEFINITIONS);
export function getAdminFormDefinition(formKey){return ADMIN_FORM_DEFINITIONS[formKey]??null;}
