/** KFE Admin source-record form definitions. Derived values are never entered here. */
const text=(key,label,options={})=>({key,label,type:'text',...options});
const number=(key,label,options={})=>({key,label,type:'number',...options});
const date=(key,label,options={})=>({key,label,type:'date',...options});
const select=(key,label,options=[],extra={})=>({key,label,type:'select',options,...extra});
const checkbox=(key,label,options={})=>({key,label,type:'checkbox',...options});
const textarea=(key,label,options={})=>({key,label,type:'textarea',...options});
export const ADMIN_FORM_DEFINITIONS={
vehicle:{key:'vehicle',title:'Vehicle',createLabel:'Vehicle',category:'businessSetup',fields:[text('registrationNumber','Registration number',{required:true}),text('make','Make',{required:true}),text('model','Model',{required:true}),text('variant','Variant'),date('acquiredOn','Acquisition date',{required:true}),number('acquisitionValue','Acquisition cost/value',{min:0}),number('openingOdometerKm','Opening odometer (km)',{required:true,min:0}),select('fuelType','Fuel type',['CNG','Petrol','Diesel','Electric','Hybrid'],{required:true}),number('tankCapacity','Tank / battery capacity',{min:0}),select('status','Vehicle status',['Active','Inactive','Sold'],{required:true}),date('statusDate','Status date'),date('expiryDate','Expiry date'),number('sellPrice','Sell price',{min:0}),date('saleDate','Sale date'),checkbox('active','Active',{defaultValue:true}),textarea('notes','Notes')]},
driver:{key:'driver',title:'Driver',createLabel:'Driver',category:'businessSetup',fields:[text('name','Full name',{required:true}),text('phone','Phone number'),text('licenseNumber','Driving licence number'),date('licenseExpiry','Licence expiry'),date('joinedOn','Joined on'),select('status','Status',['Active','Inactive','Suspended'],{required:true}),select('vehicleId','Assigned vehicle',[]),textarea('notes','Notes')]},
compliance:{key:'compliance',title:'Compliance',createLabel:'Compliance Record',category:'vehicleRecords',fields:[select('vehicleId','Vehicle',[],{required:true}),text('complianceType','Compliance name',{required:true}),date('validFrom','Validity · From',{required:true}),date('validUntil','Validity · Upto',{required:true}),number('cost','Amount paid',{required:true,min:0,exclusiveMin:true})]},
maintenance:{key:'maintenance',title:'Maintenance',createLabel:'Maintenance Record',category:'vehicleRecords',fields:[select('vehicleId','Vehicle',[],{required:true}),text('maintenanceType','Maintenance name / description',{required:true}),date('performedOn','Date',{required:true}),number('cost','Amount paid',{required:true,min:0,exclusiveMin:true})]},
loan:{key:'loan',title:'Loan',collectionTitle:'Loans',createLabel:'Loan',category:'finance',calculationRole:'authoritative',fields:[text('lender','Lender',{required:true}),text('accountReference','Account reference'),number('principal','Loan amount',{required:true,min:0,exclusiveMin:true}),number('tenureMonths','Tenure (months)',{required:true,min:1}),date('startDate','Loan start date',{required:true}),number('annualInterestRatePercent','Annual interest rate (%)',{required:true,min:0}),select('status','Loan status',['Active','Closed','Settled'],{required:true}),textarea('notes','Notes')]},
loanPayment:{key:'loanPayment',title:'Loan Payments',createLabel:'Loan Payment',category:'finance',calculationRole:'authoritative-payment-record',fields:[select('loanId','Loan',[],{required:true}),date('paidOn','Actual payment date',{required:true}),number('amount','Actual amount paid',{required:true,min:0,exclusiveMin:true}),textarea('notes','Notes')]},
prepayment:{key:'prepayment',title:'Prepayments',createLabel:'Prepayment',category:'finance',calculationRole:'authoritative-prepayment-record',fields:[select('loanId','Loan',[],{required:true}),date('paidOn','Prepayment date',{required:true}),number('amount','Actual prepayment amount',{required:true,min:0,exclusiveMin:true}),textarea('reason','Reason'),textarea('notes','Notes')]},
settlement:{key:'settlement',title:'Payments',createLabel:'Payment',category:'finance',calculationRole:'authoritative-settlement-record',fields:[select('settlementType','Settlement type',['Payment'],{required:true,defaultValue:'Payment'}),select('sourceType','Paying for',['Maintenance','Compliance'],{required:true}),select('sourceId','Source record',[],{required:true}),date('settledOn','Payment date',{required:true}),number('amount','Amount paid',{required:true,min:0,exclusiveMin:true}),select('paymentMethod','Payment method',['Cash','Bank transfer','UPI','Card','Cheque','Other']),text('referenceNumber','Payment reference'),textarea('notes','Notes')]},
driverTarget:{key:'driverTarget',title:'Driver Monthly Target',createLabel:'Driver Monthly Target',category:'planningControls',calculationRole:'authoritative',fields:[select('driverId','Driver',[],{required:true}),date('effectiveFrom','Month',{required:true}),number('desiredDriverProfit','Monthly target',{required:true,min:0}),checkbox('active','Active',{defaultValue:true}),textarea('notes','Notes')]},
breakEvenInputs:{key:'breakEvenInputs',title:'Maintenance per KM',createLabel:'Maintenance Rate',category:'planningControls',calculationRole:'authoritative-inputs',fields:[date('effectiveFrom','Change date',{required:true}),number('maintenanceProvisionPerKm','Maintenance provision per vehicle km',{required:true,min:0,defaultValue:2}),textarea('notes','Notes')]}
};
export const ADMIN_FORM_KEYS=Object.keys(ADMIN_FORM_DEFINITIONS);
export function getAdminFormDefinition(formKey){return ADMIN_FORM_DEFINITIONS[formKey]??null;}