/** Universal Admin validation: normalization, field constraints and source-record integrity gates. */
export const UNIVERSAL_FORM_RULES={trimText:true,rejectUnknownFields:true,requiredFieldsMustBePresent:true,numbersMustBeFinite:true,numbersMustRespectBounds:true,datesMustBeValid:true,selectValuesMustBeAllowed:true,validateBeforeSave:true};
const blank=v=>v===undefined||v===null||String(v).trim()==='';
const dateValue=v=>Date.parse(v);
const optionValue=option=>option&&typeof option==='object'&&'value' in option?option.value:option;
export function normalizeFormValues(definition,values={}){const out={};for(const f of definition.fields??[]){let v=values[f.key];if(v===undefined&&f.defaultValue!==undefined)v=f.defaultValue;if(['text','textarea','select'].includes(f.type)&&typeof v==='string'&&UNIVERSAL_FORM_RULES.trimText)v=v.trim();if(f.type==='number'&&!blank(v))v=Number(v);if(f.type==='checkbox'){if(typeof v==='string')v=['true','1','yes','on'].includes(v.trim().toLowerCase());else v=Boolean(v)};out[f.key]=v}return out}
export function validateAdminForm(definition,values={},context={}){const errors={},normalized=normalizeFormValues(definition,values),allowed=new Set((definition.fields??[]).map(f=>f.key));if(UNIVERSAL_FORM_RULES.rejectUnknownFields)for(const k of Object.keys(values))if(!allowed.has(k))errors[k]='Unknown field is not permitted.';const relaxed=new Set(context.relaxRequired??[]);for(const f of definition.fields??[]){const v=normalized[f.key];if(f.required&&!relaxed.has(f.key)&&blank(v)){errors[f.key]=`${f.label} is required.`;continue}if(blank(v))continue;if(f.type==='number'&&!Number.isFinite(v))errors[f.key]=`${f.label} must be a valid number.`;else if(f.type==='number'&&f.exclusiveMin&&f.min!==undefined&&v<=f.min)errors[f.key]=`${f.label} must be greater than ${f.min}.`;else if(f.type==='number'&&f.min!==undefined&&v<f.min)errors[f.key]=`${f.label} must be at least ${f.min}.`;else if(f.type==='number'&&f.max!==undefined&&v>f.max)errors[f.key]=`${f.label} must be at most ${f.max}.`;if(['date','datetime-local'].includes(f.type)&&Number.isNaN(dateValue(v)))errors[f.key]=`${f.label} must be a valid date/time.`;if(f.type==='select'&&f.options?.length&&!f.options.some(option=>optionValue(option)===v))errors[f.key]=`${f.label} has an invalid selection.`}
if(definition.key==='vehicle'&&normalized.status==='Sold'&&blank(normalized.saleDate))errors.saleDate='Sale date is required when vehicle status is Sold.';
if(definition.key==='vehicle'&&normalized.status==='Sold'&&blank(normalized.sellPrice))errors.sellPrice='Sell price is required when vehicle status is Sold.';
if(definition.key==='vehicle'&&normalized.saleDate&&normalized.status!=='Sold')errors.saleDate='Sale date is only valid for a Sold vehicle.';
if(definition.key==='vehicle'&&normalized.expiryDate&&normalized.statusDate&&dateValue(normalized.expiryDate)<dateValue(normalized.statusDate))errors.expiryDate='Expiry date cannot precede status date.';
if(definition.key==='compliance'&&normalized.validUntil&&normalized.validFrom&&dateValue(normalized.validUntil)<dateValue(normalized.validFrom))errors.validUntil='Valid until cannot precede valid from.';
if(definition.key==='driver'&&normalized.licenseExpiry&&normalized.joinedOn&&dateValue(normalized.licenseExpiry)<dateValue(normalized.joinedOn))errors.licenseExpiry='Licence expiry cannot precede joined date.';
if(['driverTarget','breakEvenInputs'].includes(definition.key)&&normalized.effectiveUntil&&normalized.effectiveFrom&&dateValue(normalized.effectiveUntil)<dateValue(normalized.effectiveFrom))errors.effectiveUntil='Effective until cannot precede effective from.';
if(definition.key==='loanPayment'&&!blank(normalized.amount)&&!blank(normalized.principalComponent)&&!blank(normalized.interestComponent)&&normalized.principalComponent+normalized.interestComponent>normalized.amount+0.01)errors.amount='Principal and interest components cannot exceed actual amount paid.';
if(definition.key==='prepayment'&&!blank(normalized.outstandingAfter)&&!blank(normalized.outstandingBefore)&&normalized.outstandingAfter>normalized.outstandingBefore+0.01)errors.outstandingAfter='Outstanding principal after prepayment cannot exceed the amount before prepayment.';
if(definition.key==='settlement'){if(normalized.settlementType!=='Payment')errors.settlementType='Only payment settlements are supported here.';if(!['Maintenance','Compliance'].includes(normalized.sourceType))errors.sourceType='Payments can only be linked to Maintenance or Compliance records.';}
if(definition.key==='ride'){if(normalized.tripEndAt&&normalized.tripStartAt&&dateValue(normalized.tripEndAt)<dateValue(normalized.tripStartAt))errors.tripEndAt='Ride end cannot precede ride start.';if(normalized.status==='COMPLETED'&&blank(normalized.tripEndAt))errors.tripEndAt='Ride end is required for a completed ride.';if(normalized.status==='CANCELLED'&&blank(normalized.cancelReason))errors.cancelReason='Cancellation reason is required for a cancelled ride.';if(normalized.status==='CANCELLED'&&blank(normalized.cancelledRevenue)&&!blank(normalized.revenue))errors.cancelledRevenue='Enter cancellation revenue separately or leave revenue blank.';if(normalized.status==='COMPLETED'&&blank(normalized.revenue))errors.revenue='Fare / revenue is required for a completed ride.';if(normalized.status==='COMPLETED'&&blank(normalized.tripKm))errors.tripKm='Ride distance is required for a completed ride.';}
return{valid:Object.keys(errors).length===0,errors,values:normalized};}
