<script setup>
import { onMounted, ref } from 'vue'
import { BackupService } from '../../application/backup/backupService.js'
import { BackupConfig } from '../../application/backup/backupConfig.js'
import { CloudBackupLifecycle } from '../../application/backup/cloudBackupLifecycle.js'
import { downloadBackupText, readBackupFileText } from '../../presentation/backup/backupFileAdapter.js'

const fileInput = ref(null); const status = ref(null); const cloudConfig = ref({ enabled:false, path:'/Apps/KFE/kfe-latest-backup.json', accessToken:'', hasAccessToken:false, lastCloudBackupAt:null }); const pendingRestore = ref(null); const loading = ref(false); const error = ref(''); const notice = ref(''); const cloudNeedsReauth = ref(false)
const refresh = async () => { error.value=''; try { const local=await BackupService.getLocalBackup(); status.value=local?{savedAt:local.savedAt,...BackupService.getBackupSummary(local.backup)}:null; cloudConfig.value=await BackupConfig.getBackupConfiguration() } catch(e){error.value=e.message||'Unable to read backup status.'} }
const create=async()=>{loading.value=true;error.value='';notice.value='';try{const backup=await BackupService.createBackup();await BackupService.saveLocalBackup(backup);downloadBackupText(BackupService.serializeBackup(backup),`kfe-backup-${backup.exportedAt.replace(/[:.]/g, '-')}.json`);notice.value=`Backup created: ${BackupService.getBackupSummary(backup).totalRecords} records.`;await refresh()}catch(e){error.value=e.message||'Backup creation failed.'}finally{loading.value=false}}
const chooseRestoreFile=()=>fileInput.value?.click()
const onFile=async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;error.value='';notice.value='';try{const backup=BackupService.readBackupText(await readBackupFileText(file));pendingRestore.value={backup,summary:BackupService.getBackupSummary(backup),name:file.name}}catch(e){pendingRestore.value=null;error.value=e.message||'Backup file validation failed.'}}
const confirmRestore=async()=>{if(!pendingRestore.value)return;if(!confirm(`Restore ${pendingRestore.value.summary.totalRecords} records from ${pendingRestore.value.name}? This replaces the current KFE dataset.`))return;loading.value=true;error.value='';notice.value='';try{const summary=await BackupService.restoreBackup(pendingRestore.value.backup);pendingRestore.value=null;notice.value=`Restore completed: ${summary.totalRecords} records restored.`;await refresh()}catch(e){error.value=e.message||'Restore failed. The canonical transaction was rolled back if persistence failed.'}finally{loading.value=false}}
const restoreLocal=async()=>{const local=await BackupService.getLocalBackup();if(!local){error.value='No local backup is available.';return}pendingRestore.value={backup:local.backup,summary:BackupService.getBackupSummary(local.backup),name:'Latest local backup'}}
const saveCloudConfig=async()=>{loading.value=true;error.value='';notice.value='';try{const saved=await BackupConfig.saveBackupConfiguration(cloudConfig.value);cloudConfig.value={...saved,accessToken:''};cloudNeedsReauth.value=false;notice.value=saved.enabled?'Dropbox backup enabled.':'Dropbox daily cloud backup disabled.';await CloudBackupLifecycle.registerDailyCloudBackupSchedule()}catch(e){error.value=e.message||'Cloud configuration failed.';cloudNeedsReauth.value=true}finally{loading.value=false}}
const clearCloudConfig=async()=>{await BackupConfig.clearBackupConfiguration();cloudConfig.value=await BackupConfig.getBackupConfiguration();notice.value='Dropbox configuration cleared.'}
const backupCloudNow=async()=>{loading.value=true;error.value='';notice.value='';try{const result=await CloudBackupLifecycle.backupToConfiguredCloud();if(result.status==='backed-up'){cloudNeedsReauth.value=false;notice.value=`Dropbox backup completed at ${result.completedAt}.`}else if(result.status==='disabled'){cloudNeedsReauth.value=true;error.value='Enable Dropbox and provide an access token first.'}else if(result.status==='failed'){cloudNeedsReauth.value=true;error.value=result.error?.message||'Dropbox backup failed. Re-enter the Dropbox access token if the connection has expired.'}else notice.value='Dropbox backup is already current.';await refresh()}catch(e){cloudNeedsReauth.value=true;error.value=e.message||'Dropbox backup failed. Re-enter the Dropbox access token if the connection has expired.'}finally{loading.value=false}}
const restoreCloud=async()=>{if(!confirm('Restore the latest Dropbox backup? This replaces the current KFE dataset.'))return;loading.value=true;error.value='';notice.value='';try{const summary=await CloudBackupLifecycle.restoreFromConfiguredCloud();notice.value=`Dropbox restore completed: ${summary.totalRecords} records restored.`;await refresh()}catch(e){error.value=e.message||'Dropbox restore failed.'}finally{loading.value=false}}
onMounted(refresh)
</script>
<template><section class="backup-panel" aria-label="Backup and restore"><div class="actions"><button class="primary" :disabled="loading" @click="create">Create backup</button><button :disabled="loading" @click="chooseRestoreFile">Restore from phone</button><input ref="fileInput" type="file" accept="application/json,.json" hidden @change="onFile" /></div><div class="cloud"><strong>Dropbox</strong><label><input v-model="cloudConfig.enabled" type="checkbox" /> Enable daily backup</label><div v-if="!cloudConfig.hasAccessToken || cloudNeedsReauth" class="token-config"><label>Dropbox access token<input v-model="cloudConfig.accessToken" type="password" autocomplete="off" spellcheck="false" placeholder="Enter token to connect" /></label><small v-if="cloudConfig.hasAccessToken && cloudNeedsReauth">Connection needs attention. Re-enter the token if required.</small><button :disabled="loading || !cloudConfig.enabled || !cloudConfig.accessToken" @click="saveCloudConfig">Save connection</button></div><div v-else class="connected"><span>✓ Dropbox connected</span><button :disabled="loading || !cloudConfig.enabled" @click="backupCloudNow">Back up now</button><button :disabled="loading || !cloudConfig.enabled" @click="restoreCloud">Restore</button><button :disabled="loading" @click="clearCloudConfig">Disconnect</button></div><small v-if="cloudConfig.lastCloudBackupAt">Last backup: {{cloudConfig.lastCloudBackupAt}}</small></div><div v-if="pendingRestore" class="pending"><strong>Validated backup ready</strong><p>{{pendingRestore.name}} · {{pendingRestore.summary.totalRecords}} total records · exported {{pendingRestore.summary.exportedAt}}</p><button class="danger" :disabled="loading" @click="confirmRestore">Confirm restore</button><button :disabled="loading" @click="pendingRestore=null">Cancel</button></div><p v-if="error" class="error">{{error}}</p><p v-if="notice" class="notice">{{notice}}</p><div class="status"><strong>Latest local recovery copy</strong><span v-if="status">{{status.totalRecords}} records · {{status.savedAt}}</span><span v-else>No local backup created yet.</span></div></section></template>
<style scoped>.backup-panel{margin-top:10px;border:1px solid #e2e8f0;border-radius:12px;background:#fff;padding:11px}.actions,.cloud-actions,.connected{display:flex;gap:7px;flex-wrap:wrap}.actions button,.pending button,.connected button,.token-config button{border:1px solid #cbd5e1;background:#fff;border-radius:9px;padding:9px 11px;font-weight:650}.actions .primary{background:#0f172a;color:#fff;border-color:#0f172a}.cloud,.pending,.status{margin-top:9px;padding:10px;border-radius:9px;background:#f8fafc;font-size:.72rem}.cloud strong,.status strong,.pending strong{display:block}.cloud label{display:grid;gap:4px;margin:7px 0;font-size:.7rem;font-weight:650}.cloud label:first-of-type{display:flex;align-items:center;gap:7px}.cloud input[type=password]{width:100%;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:7px;padding:8px;background:#fff}.token-config{display:grid;gap:6px}.token-config small,.connected span{color:#64748b;font-size:.65rem}.connected{align-items:center}.pending{border:1px solid #cbd5e1}.danger{background:#7f1d1d!important;color:#fff;border-color:#7f1d1d!important}.error{color:#b42318;background:#fef3f2;padding:9px;border-radius:8px;font-size:.75rem}.notice{color:#166534;background:#f0fdf4;padding:9px;border-radius:8px;font-size:.75rem}.status{display:flex;justify-content:space-between;gap:10px}@media(max-width:640px){.status{flex-direction:column}}</style>
