import { describe, expect, it } from "vitest"
import { MovementAccountingService, filterGpsTrace, haversineDistanceKm } from "../../domain/movement/movementAccounting.js"
const garage = { latitude: 19, longitude: 72, accuracy: 5 }
const pickup1 = { latitude: 19.01, longitude: 72, accuracy: 5 }; const drop1 = { latitude: 19.02, longitude: 72, accuracy: 5 }; const pickup2 = { latitude: 19.03, longitude: 72, accuracy: 5 }; const drop2 = { latitude: 19.04, longitude: 72, accuracy: 5 }
const trips = [{ id: "trip-1", status: "COMPLETED", tripStartAt: "2026-09-12T08:00:00Z", tripEndAt: "2026-09-12T08:30:00Z", tripStartLocation: pickup1, tripEndLocation: drop1 }, { id: "trip-2", status: "COMPLETED", tripStartAt: "2026-09-12T09:00:00Z", tripEndAt: "2026-09-12T09:30:00Z", tripStartLocation: pickup2, tripEndLocation: drop2 }]

describe("MovementAccountingService", () => {
  it("calculates the expected in-shift movement segments", async () => { const result = await MovementAccountingService.calculateDeadMiles({ garageLocation: garage, trips }); expect(result.segments).toHaveLength(5); expect(result.segments.map(s=>s.label)).toEqual(["GARAGE_TO_FIRST_PICKUP","TRIP_1_BUSINESS","TRIP_1_END_TO_TRIP_2_START","TRIP_2_BUSINESS","LAST_TRIP_TO_GARAGE"]); expect(result.segments.filter(s=>s.classification === "DEAD")).toHaveLength(3); expect(result.deadMilesKm).toBeGreaterThan(0); expect(result.businessMilesKm).toBeGreaterThan(0); expect(haversineDistanceKm(garage,pickup1)).toBeGreaterThan(0) })
  it("classifies the authoritative odometer remainder as dead km", async () => { const result = await MovementAccountingService.reconcileShiftMovement({ garageLocation: garage, trips, startOdometer: 100, endOdometer: 120 }); const remainder = result.segments.find(s=>s.authority === "ODOMETER_REMAINDER"); expect(remainder?.classification).toBe("DEAD"); expect(result.unclassifiedKm).toBe(0); expect(result.deadMilesKm).toBeGreaterThanOrEqual(remainder.distanceKm) })
  it("reconciles without a garage GPS point and leaves no unclassified in-shift remainder", async () => { const result = await MovementAccountingService.reconcileShiftMovement({ garageLocation: null, trips: [trips[0]], startOdometer: 100, endOdometer: 110 }); expect(result.reconciliationStatus).toBe("RECONCILED"); expect(result.unclassifiedKm).toBe(0); expect(result.segments.some(s=>s.authority === "ODOMETER_REMAINDER" && s.classification === "DEAD")).toBe(true) })
  it("upgrades only manually reconciled Uber Business KM to authoritative", async () => { const result = await MovementAccountingService.reconcileShiftMovement({ garageLocation: garage, trips, startOdometer: 100, endOdometer: 105, manualBusinessKmByTripId: { "trip-1": 2.5 } }); const trip1=result.segments.find(s=>s.tripId==="trip-1"); const trip2=result.segments.find(s=>s.tripId==="trip-2"); expect(trip1.distanceKm).toBe(2.5); expect(trip1.authority).toBe("MANUAL_UBER"); expect(trip2.authority).toBe("GPS_ESTIMATE") })
  it("flags an over-estimated GPS/manual movement total", async () => { const result=await MovementAccountingService.reconcileShiftMovement({garageLocation:garage,trips,startOdometer:100,endOdometer:100.1,manualBusinessKmByTripId:{"trip-1":5}}); expect(result.reconciliationStatus).toBe("OVER_ESTIMATE"); expect(result.unclassifiedKm).toBe(0); expect(result.reconciliationDifferenceKm).toBeLessThan(0) })
  it("handles a missing trip endpoint without fabricating distance", async () => { const missing=await MovementAccountingService.calculateDeadMiles({garageLocation:garage,trips:[{...trips[0],tripEndLocation:null}]}); expect(missing.segments.find(s=>s.tripId==="trip-1").distanceKm).toBeNull() })
  it("removes stationary GPS jitter",()=>{const trace=filterGpsTrace([{latitude:19,longitude:72,accuracy:5,speed:0,capturedAt:"2026-09-12T08:00:00Z"},{latitude:19.00005,longitude:72.00002,accuracy:5,speed:0,capturedAt:"2026-09-12T08:01:00Z"},{latitude:19.001,longitude:72,accuracy:5,speed:10,capturedAt:"2026-09-12T08:02:00Z"}]); expect(trace).toHaveLength(2)})
  it("rejects low-quality GPS fixes",()=>{expect(filterGpsTrace([{latitude:19,longitude:72,accuracy:100,speed:20,capturedAt:"2026-09-12T08:00:00Z"}])).toHaveLength(0)})
  it("reconstructs the waiting anchor",()=>{const anchor=MovementAccountingService.waitingAnchorForTrace([{latitude:19,longitude:72,accuracy:5,speed:0,capturedAt:"2026-09-12T08:00:00Z"},{latitude:19.0003,longitude:72.0003,accuracy:5,speed:0,capturedAt:"2026-09-12T08:01:00Z"},{latitude:19.001,longitude:72.001,accuracy:5,speed:8,capturedAt:"2026-09-12T08:02:00Z"}]); expect(anchor.capturedAt).toBe("2026-09-12T08:01:00Z")})
  it("uses the replaceable routing engine and preserves matched geometry",async()=>{let calls=0;const router={routeTrace:async()=>{calls+=1;return{provider:"test-router",method:"TEST_MAP_MATCH",confidence:"ESTIMATED_ROAD_TRACE",distanceKm:4.2,geometry:{type:"LineString",coordinates:[[72,19],[72.01,19.01]]},provenance:{provider:"test-router",operation:"trace"}}}};const result=await MovementAccountingService.calculateSegments({garageLocation:garage,trips:[trips[0]],router,gpsSnapshots:[{latitude:19.005,longitude:72,accuracy:5,speed:8,capturedAt:"2026-09-12T08:10:00Z"},{latitude:19.015,longitude:72,accuracy:5,speed:8,capturedAt:"2026-09-12T08:20:00Z"}]});expect(calls).toBeGreaterThan(0);expect(result.segments[0].routingProvenance.provider).toBe("test-router")})
  it("does not label filtered GPS fallback as road-matched geometry",async()=>{const router={routeTrace:async()=>null};const result=await MovementAccountingService.calculateSegments({garageLocation:garage,trips:[trips[0]],router,gpsSnapshots:[{latitude:19.005,longitude:72,accuracy:5,speed:8,capturedAt:"2026-09-12T08:10:00Z"},{latitude:19.015,longitude:72,accuracy:5,speed:8,capturedAt:"2026-09-12T08:20:00Z"}]});expect(result.segments[0].roadMatchedGeometry).toBeNull()})
  it("rejects a backwards odometer and handles zero distance",async()=>{await expect(MovementAccountingService.reconcileShiftMovement({garageLocation:garage,trips:[],startOdometer:120,endOdometer:119})).rejects.toThrow();const result=await MovementAccountingService.reconcileShiftMovement({garageLocation:garage,trips:[],startOdometer:120,endOdometer:120});expect(result.unclassifiedKm).toBe(0);expect(result.reconciliationStatus).toBe("RECONCILED")})
})
