<script setup>
import {onMounted,onBeforeUnmount,ref,watch} from 'vue';
import {clearFormDraft,discardFormDraft,hasFormDraft} from '../../js/ui/form-drafts.js';
const props=defineProps({draftKey:{type:String,required:true},title:{type:String,required:true},subtitle:{type:String,default:''},initialValue:{type:Object,default:()=>({})},saving:{type:Boolean,default:false},valid:{type:Boolean,default:true},formType:{type:String,default:''}});const emit=defineEmits(['save','discard','change','close']);const formRef=ref(null),value=ref({...props.initialValue}),hasDraft=ref(false),dirty=ref(false);let submitTimer=null;const SUBMIT_COOLDOWN_MS=750;
function refreshDraftState(){hasDraft.value=hasFormDraft(formRef.value);}
function clearDraft(){if(formRef.value)clearFormDraft(formRef.value);hasDraft.value=false;dirty.value=false;}
function onSubmit(){if(props.saving||!props.valid||submitTimer)return;emit('save',{...value.value});submitTimer=setTimeout(()=>{submitTimer=null;},SUBMIT_COOLDOWN_MS);}
function discard(){discardFormDraft(formRef.value);value.value={...props.initialValue};hasDraft.value=false;dirty.value=false;emit('discard');}
function requestClose(){if(props.saving)return;if(dirty.value||hasDraft.value){const confirmed=globalThis.confirm?.('Discard your unsaved changes?')??true;if(!confirmed)return;clearDraft();}emit('discard');emit('close');}
watch(value,next=>{dirty.value=true;emit('change',{...next});},{deep:true});onMounted(refreshDraftState);onBeforeUnmount(()=>{clearTimeout(submitTimer);});
</script>
<template><form ref="formRef" class="kfe-form-shell" :data-kfe-draft-form="draftKey" data-kfe-form-architecture="universal" :data-form-type="formType||undefined" @submit.prevent="onSubmit"><header class="kfe-form-heading"><div><p class="kfe-eyebrow">KFE 2.0</p><h1>{{title}}</h1><p v-if="subtitle" class="kfe-destination-subtitle">{{subtitle}}</p></div><div class="kfe-form-heading-actions"><span v-if="hasDraft" class="kfe-draft-badge">Unsaved draft</span><button type="button" class="kfe-secondary-action" :disabled="saving" @click="requestClose">Close</button></div></header><div class="kfe-form-body" data-kfe-form-section="default"><slot :value="value" /></div><footer class="kfe-form-actions"><button v-if="hasDraft" type="button" class="kfe-secondary-action" :disabled="saving" @click="discard">Discard draft</button><button type="submit" class="kfe-primary-action" :disabled="saving||!valid"><span v-if="saving">Saving…</span><span v-else>Save</span></button></footer></form></template>
