<script setup>
import { ref } from 'vue'

const props=defineProps({application:{type:Object,required:true}})
const busy=ref(false),message=ref(''),error=ref(''),fileInput=ref(null)
function requestFile(){fileInput.value?.click()}
async function backup(){busy.value=true;message.value='';error.value='';try{const payload=await props.application.exportBackup();const blob=new Blob([JSON.stringify(payload)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`kfe-backup-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(url);message.value='Backup created.'}catch(e){error.value=`Backup failed: ${String(e?.message||e)}`}finally{busy.value=false}}
async function restore(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;busy.value=true;message.value='';error.value='';try{const payload=JSON.parse(await file.text());if(!payload||typeof payload!=='object')throw Error('This is not a valid KFE backup.');if(!confirm('Restore this backup? Existing local ERP data will be replaced.'))return;await props.application.restoreBackup(payload);message.value='Restore complete. Reloading KFE…';setTimeout(()=>location.reload(),700)}catch(e){error.value=`Restore failed: ${String(e?.message||e)}`}finally{busy.value=false}}
async function resetData(){if(!confirm('RESET ALL KFE DATA? This permanently removes local ERP records from this device.'))return;if(!confirm('Final confirmation: erase all local ERP data?'))return;busy.value=true;message.value='';error.value='';try{await props.application.resetAllData();message.value='Local data reset. Reloading…';setTimeout(()=>location.reload(),500)}catch(e){error.value=`Reset failed: ${String(e?.message||e)}`;busy.value=false}}
</script>
<template>
<section class="kfe-settings-page" aria-labelledby="settings-title"><header class="kfe-page-head"><span class="kfe-eyebrow">DATA SAFETY</span><h1 id="settings-title">Backup & restore</h1><p>Protect the complete local KFE dataset or erase it when required.</p></header>
<div v-if="error" class="kfe-alert is-error" role="alert">{{error}}</div><div v-if="message" class="kfe-alert is-ok" role="status">✓ {{message}}</div>
<section class="kfe-settings-card" aria-labelledby="backup-title"><span class="kfe-card-kicker">BACKUP</span><h2 id="backup-title">Backup & restore</h2><p>Export the complete local ERP dataset to a portable backup, or restore a backup onto this device.</p><div class="kfe-settings-actions"><button class="kfe-action-primary" :disabled="busy" @click="backup">Export backup</button><button class="kfe-action-secondary" :disabled="busy" @click="requestFile">Restore backup</button><input ref="fileInput" hidden type="file" accept="application/json,.json" @change="restore"></div></section>
<section class="kfe-settings-card danger" aria-labelledby="reset-title"><span class="kfe-card-kicker">DANGER ZONE</span><h2 id="reset-title">Data reset</h2><p>Erase all local ERP records from this device. This cannot be undone.</p><button class="kfe-action-danger" :disabled="busy" @click="resetData">Reset all local data</button></section>
</section>
</template>
<style scoped>
.kfe-settings-page{display:grid;gap:14px;padding:18px 16px 112px;max-width:720px;margin:auto}.kfe-page-head{display:grid;gap:5px;padding:2px 2px 4px}.kfe-page-head h1{margin:0;font-size:clamp(1.75rem,7vw,2.15rem);letter-spacing:-.03em}.kfe-page-head p,.kfe-settings-card p{margin:0;color:var(--kfe-muted-text);line-height:1.45}.kfe-settings-card{background:var(--kfe-ui-surface);border:1px solid var(--kfe-ui-border);border-radius:20px;padding:18px;box-shadow:var(--kfe-ui-shadow);display:grid;gap:11px}.kfe-settings-card h2{margin:0;font-size:1.05rem}.kfe-card-kicker{font-size:.67rem;text-transform:uppercase;letter-spacing:.1em;font-weight:900;color:var(--kfe-accent)}.kfe-settings-actions{display:grid;grid-template-columns:1fr 1fr;gap:9px}.kfe-settings-actions button,.kfe-action-danger{min-height:52px;border-radius:14px;padding:0 14px;font-weight:900}.kfe-action-primary{border:0;background:var(--kfe-accent);color:#fff}.kfe-action-secondary{border:1px solid var(--kfe-ui-border);background:var(--kfe-ui-bg);color:var(--kfe-ui-text)}.kfe-action-danger{border:1px solid var(--kfe-danger);background:transparent;color:var(--kfe-danger);width:100%}.danger{border-color:color-mix(in srgb,var(--kfe-danger) 40%,var(--kfe-ui-border))}.kfe-alert{padding:12px 14px;border-radius:14px;font-weight:700}.is-error{background:color-mix(in srgb,var(--kfe-danger) 14%,var(--kfe-ui-surface));color:var(--kfe-danger)}.is-ok{background:color-mix(in srgb,var(--kfe-success) 14%,var(--kfe-ui-surface));color:var(--kfe-success)}@media(max-width:480px){.kfe-settings-actions{grid-template-columns:1fr}.kfe-settings-card{padding:16px}}
</style>
