<script setup>
import { onMounted, ref } from 'vue';
import KfeFormShell from './KfeFormShell.vue';
import KfeFormField from './KfeFormField.vue';
import KfeStatePanel from './KfeStatePanel.vue';
const props=defineProps({application:{type:Object,required:true}});const emit=defineEmits(['back','calculation-request','open']);
const detail=ref('');const activeForm=ref('');const model=ref({loan:null,payments:[],amortization:[],loans:[]});
const initialLoan={principal:'',annual_rate_percent:'',term_months:'',emi:'',start_date:new Date().toISOString().slice(0,10),vehicle_id:''};
async function refresh(){model.value=await props.application.getLoanReadModel();}onMounted(()=>{void refresh();});
function openDetail(name){detail.value=name;activeForm.value='';emit('open',{module:'Loans',detail:name});}function closeDetail(){detail.value='';}
function savePrepayment(value){emit('calculation-request',{module:'Loans',action:'PREPAYMENT_CALCULATE',value});}
async function saveLoan(value){await props.application.createLoan({principal:Math.round(Number(value.principal)*100),annual_rate_percent:Number(value.annual_rate_percent),term_months:Number(value.term_months),emi:Math.round(Number(value.emi)*100),start_date:value.start_date,vehicle_id:value.vehicle_id||null});activeForm.value='';await refresh();}
async function savePayment(value){if(!model.value.loan)throw new Error('No active loan');await props.application.recordLoanPayment({loan_id:model.value.loan.id,amount:Math.round(Number(value.amount)*100),date:value.date});activeForm.value='';await refresh();}
</script>
<template><section class="kfe-module-view" aria-labelledby="loan-title">
<div v-if="!detail&&!activeForm"><button class="kfe-secondary-action kfe-back-action" type="button" @click="emit('back')">‹ More</button><p class="kfe-eyebrow">Money</p><h1 id="loan-title">Loans</h1><p class="kfe-destination-subtitle">Understand current obligations without exposing unnecessary accounting complexity.</p>
<article class="kfe-detail-card"><div class="kfe-detail-card__top"><div><span class="kfe-card-label">Loan status</span><strong>{{model.loan?.status||'No active loan'}}</strong></div><span class="kfe-state-badge">Current</span></div><dl class="kfe-detail-list"><div><dt>EMI</dt><dd>{{model.loan?`₹${(Number(model.loan.emi_paise)/100).toFixed(2)}`:'—'}}</dd></div><div><dt>Outstanding balance</dt><dd>{{model.loan?`₹${(Number(model.loan.remaining_balance_paise)/100).toFixed(2)}`:'—'}}</dd></div><div><dt>Vehicle association</dt><dd>{{model.loan?.vehicle_id||'Authoritative vehicle'}}</dd></div></dl></article>
<section class="kfe-module-section"><h2>Loan lifecycle</h2><div class="kfe-module-list"><button type="button" @click="activeForm='create-loan'">Create loan</button><button v-if="model.loan" type="button" @click="activeForm='record-payment'">Record payment</button></div></section>
<section class="kfe-module-section"><h2>Payment</h2><button class="kfe-list-action" type="button" @click="openDetail('Payment history')"><span>Payment history</span><span aria-hidden="true">›</span></button></section>
<section class="kfe-module-section"><h2>Financial tools</h2><div class="kfe-module-list"><button type="button" @click="openDetail('Amortization schedule')"><span>Amortization schedule</span><span aria-hidden="true">›</span></button><button type="button" @click="activeForm='prepayment'"><span>Prepayment calculator</span><span aria-hidden="true">›</span></button></div><p class="kfe-form-boundary-note">Prepayment charges: <strong>Zero</strong>. Calculation remains authoritative outside presentation.</p></section></div>
<KfeFormShell v-else-if="activeForm==='create-loan'" draft-key="loan-create" title="Create loan" subtitle="Loan terms are persisted through the application boundary."><template #default="{value}"><KfeFormField id="loan-principal" label="Principal" v-model="value.principal" type="number" required/><KfeFormField id="loan-rate" label="Annual interest rate %" v-model="value.annual_rate_percent" type="number" required/><KfeFormField id="loan-term" label="Term months" v-model="value.term_months" type="number" required/><KfeFormField id="loan-emi" label="EMI" v-model="value.emi" type="number" required/><KfeFormField id="loan-start" label="Start date" v-model="value.start_date" type="date" required/><KfeFormField id="loan-vehicle" label="Vehicle association" v-model="value.vehicle_id"/><button type="button" @click="saveLoan(value)">Save loan</button><button type="button" @click="activeForm=''">Cancel</button></template></KfeFormShell>
<KfeFormShell v-else-if="activeForm==='record-payment'" draft-key="loan-payment" title="Record payment" subtitle="Principal and interest allocation is authoritative in the application layer."><template #default="{value}"><KfeFormField id="loan-payment-amount" label="Payment amount" v-model="value.amount" type="number" required/><KfeFormField id="loan-payment-date" label="Payment date" v-model="value.date" type="date" required/><button type="button" @click="savePayment(value)">Save payment</button><button type="button" @click="activeForm=''">Cancel</button></template></KfeFormShell>
<KfeFormShell v-else-if="activeForm==='prepayment'" draft-key="loan-prepayment" title="Prepayment calculator" subtitle="Zero prepayment charges. Enter the inputs; authoritative results come from the application/domain layer." :initial-value="{amount:'',date:''}" @save="savePrepayment"><template #default="{value}"><KfeFormField id="loan-prepayment-amount" label="Outstanding principal" v-model="value.amount" type="number" required/><KfeFormField id="loan-prepayment-date" label="Effective date" v-model="value.date" type="date" required/><KfeStatePanel state="normal" title="Calculation boundary" message="This screen collects inputs only. It does not calculate remaining principal, tenure, interest savings, or EMI changes."/></template></KfeFormShell>
<article v-else class="kfe-financial-detail"><button class="kfe-secondary-action" type="button" @click="closeDetail">‹ Loans</button><p class="kfe-eyebrow">DETAIL</p><h2>{{detail}}</h2><div v-if="detail==='Payment history'" class="kfe-financial-breakdown"><div v-for="payment in model.payments" :key="payment.id"><span>{{payment.date}}</span><strong>₹{{(Number(payment.payment_paise)/100).toFixed(2)}}</strong></div><div v-if="!model.payments.length"><span>Records</span><strong>No payments</strong></div></div><div v-else class="kfe-financial-breakdown"><div v-for="row in model.amortization.slice(0,12)" :key="row.month"><span>Month {{row.month}}</span><strong>₹{{(Number(row.payment_paise)/100).toFixed(2)}} · Principal ₹{{(Number(row.principal_paise)/100).toFixed(2)}} · Interest ₹{{(Number(row.interest_paise)/100).toFixed(2)}}</strong></div><div v-if="!model.amortization.length"><span>Schedule</span><strong>No active loan</strong></div></div></article>
</section></template>
