<script setup>
import { computed, onMounted, ref } from 'vue';
import KfeFormShell from './KfeFormShell.vue';

const props = defineProps({ application: { type: Object, required: true } });
const emit = defineEmits(['back','open']);
const mode=ref(null);const editingId=ref(null);const vehicles=ref([]);const assignments=ref([]);const message=ref('');const error=ref('');
const draft=ref({registration_number:'',make:'',model:'',variant:'',fuel_type:'CNG',acquisition_date:'',acquisition_type:'USED',acquisition_odometer:'',acquisition_cost:'0'});
const lifecycleDraft=ref({retirement_date:'',retirement_odometer:'',reason:''});
const saleDraft=ref({sale_date:'',sale_odometer:'',sale_amount:'',sale_reference:'',sale_notes:''});
const vehicleList=computed(()=>vehicles.value);
function blank(){return {registration_number:'',make:'',model:'',variant:'',fuel_type:'CNG',acquisition_date:'',acquisition_type:'USED',acquisition_odometer:'',acquisition_cost:'0'};}
async function load(){vehicles.value=await props.application.administrator.listVehicles();assignments.value=await props.application.administrator.listAssignments();}
function startCreate(){editingId.value=null;draft.value=blank();message.value='';error.value='';mode.value='create';}
function startEdit(v){editingId.value=v.id;draft.value={registration_number:v.registration_number,make:v.make,model:v.model,variant:v.variant||'',fuel_type:v.fuel_type,acquisition_date:v.acquisition_date,acquisition_type:v.acquisition_type,acquisition_odometer:v.acquisition_odometer,acquisition_cost:(Number(v.acquisition_cost_paise||0)/100).toFixed(2)};message.value='';error.value='';mode.value='edit';}
function startRetire(v){editingId.value=v.id;lifecycleDraft.value={retirement_date:'',retirement_odometer:v.current_odometer,reason:''};error.value='';message.value='';mode.value='retire';}
function startSell(v){editingId.value=v.id;saleDraft.value={sale_date:'',sale_odometer:v.current_odometer,sale_amount:'',sale_reference:'',sale_notes:''};error.value='';message.value='';mode.value='sell';}
async function saveVehicle(value){try{error.value='';if(editingId.value)await props.application.administrator.updateVehicle(editingId.value,value);else await props.application.administrator.createVehicle(value);mode.value=null;message.value='Vehicle saved safely.';await load();}catch(e){error.value=e?.message||String(e);}}
async function retire(value){try{error.value='';await props.application.administrator.retireVehicle(editingId.value,value);mode.value=null;message.value='Vehicle retired safely.';await load();}catch(e){error.value=e?.message||String(e);}}
async function sell(value){try{error.value='';await props.application.administrator.sellVehicle(editingId.value,value);mode.value=null;message.value='Vehicle sale recorded safely.';await load();}catch(e){error.value=e?.message||String(e);}}
function closeForm(){mode.value=null;error.value='';}
function statusLabel(v){return v.lifecycle_status==='ACTIVE'?'Active':v.lifecycle_status==='SOLD'?'Sold':v.lifecycle_status==='TRANSFERRED'?'Transferred':'Retired';}
function driversFor(v){return assignments.value.filter(a=>a.vehicle_id===v.id&&a.status==='ACTIVE'&&!a.end_date);}
onMounted(load);
</script>

<template>
<section class="kfe-module-view" aria-labelledby="vehicle-title">
  <div class="kfe-module-heading"><button class="kfe-secondary-action kfe-back-action" type="button" @click="emit('back')">‹ Administrator</button><p class="kfe-eyebrow">Administrator · Vehicle</p><h1 id="vehicle-title">Vehicles</h1><p class="kfe-destination-subtitle">Authoritative vehicle identity, odometer and lifecycle records.</p></div>
  <p v-if="message" class="kfe-success-note" role="status">{{message}}</p><p v-if="error" class="kfe-error-note" role="alert">{{error}}</p>
  <div class="kfe-form-actions"><button class="kfe-primary-action" type="button" @click="startCreate">Add Vehicle</button></div>
  <KfeFormShell v-if="mode==='create'||mode==='edit'" :draft-key="`vehicle-${editingId||'new'}`" :title="editingId?'Edit Vehicle':'Add Vehicle'" subtitle="Incomplete entry is safe; final save enforces vehicle rules." :initial-value="draft" @save="saveVehicle" @discard="closeForm">
    <template #default="{value}"><div class="kfe-form-field"><label class="kfe-form-label">Registration Number <span class="kfe-required">Required</span></label><input v-model="value.registration_number" class="kfe-form-input" autocomplete="off" /></div><div class="kfe-form-field"><label class="kfe-form-label">Make <span class="kfe-required">Required</span></label><input v-model="value.make" class="kfe-form-input" /></div><div class="kfe-form-field"><label class="kfe-form-label">Model <span class="kfe-required">Required</span></label><input v-model="value.model" class="kfe-form-input" /></div><div class="kfe-form-field"><label class="kfe-form-label">Variant / Type</label><input v-model="value.variant" class="kfe-form-input" /></div><div class="kfe-form-field"><label class="kfe-form-label">Fuel Type <span class="kfe-required">Required</span></label><input v-model="value.fuel_type" class="kfe-form-input" /></div><div class="kfe-form-field"><label class="kfe-form-label">Acquisition Date <span class="kfe-required">Required</span></label><input v-model="value.acquisition_date" class="kfe-form-input" type="date" /></div><div class="kfe-form-field"><label class="kfe-form-label">Acquisition Type <span class="kfe-required">Required</span></label><select v-model="value.acquisition_type" class="kfe-form-input"><option value="USED">Used</option><option value="NEW">New</option></select></div><div class="kfe-form-field"><label class="kfe-form-label">Acquisition Odometer <span class="kfe-required">Required</span></label><input v-model="value.acquisition_odometer" class="kfe-form-input" type="number" min="0" step="1" inputmode="numeric" /></div><div class="kfe-form-field"><label class="kfe-form-label">Acquisition Cost</label><input v-model="value.acquisition_cost" class="kfe-form-input" type="number" min="0" step="0.01" inputmode="decimal" /></div></template>
  </KfeFormShell>
  <KfeFormShell v-else-if="mode==='retire'" :draft-key="`vehicle-retire-${editingId}`" title="Retire Vehicle" subtitle="Retirement closes future operational use and preserves history." :initial-value="lifecycleDraft" @save="retire" @discard="closeForm"><template #default="{value}"><div class="kfe-form-field"><label class="kfe-form-label">Retirement Date <span class="kfe-required">Required</span></label><input v-model="value.retirement_date" class="kfe-form-input" type="date" /></div><div class="kfe-form-field"><label class="kfe-form-label">Retirement Odometer <span class="kfe-required">Required</span></label><input v-model="value.retirement_odometer" class="kfe-form-input" type="number" min="0" step="1" /></div><div class="kfe-form-field"><label class="kfe-form-label">Reason</label><textarea v-model="value.reason" class="kfe-form-input" rows="3"></textarea></div></template></KfeFormShell>
  <KfeFormShell v-else-if="mode==='sell'" :draft-key="`vehicle-sell-${editingId}`" title="Sell Vehicle" subtitle="Sale proceeds are classified separately from operating revenue and affect overall profitability." :initial-value="saleDraft" @save="sell" @discard="closeForm"><template #default="{value}"><div class="kfe-form-field"><label class="kfe-form-label">Sale Date <span class="kfe-required">Required</span></label><input v-model="value.sale_date" class="kfe-form-input" type="date" /></div><div class="kfe-form-field"><label class="kfe-form-label">Sale Odometer <span class="kfe-required">Required</span></label><input v-model="value.sale_odometer" class="kfe-form-input" type="number" min="0" step="1" /></div><div class="kfe-form-field"><label class="kfe-form-label">Sale Amount <span class="kfe-required">Required</span></label><input v-model="value.sale_amount" class="kfe-form-input" type="number" min="0" step="0.01" inputmode="decimal" /></div><div class="kfe-form-field"><label class="kfe-form-label">Reference</label><input v-model="value.sale_reference" class="kfe-form-input" /></div><div class="kfe-form-field"><label class="kfe-form-label">Notes</label><textarea v-model="value.sale_notes" class="kfe-form-input" rows="3"></textarea></div></template></KfeFormShell>
  <section v-else class="kfe-module-section"><h2>Vehicle register</h2><article v-for="vehicle in vehicleList" :key="vehicle.id" class="kfe-detail-card"><div class="kfe-detail-card__top"><div><span class="kfe-card-label">{{vehicle.registration_number}}</span><strong>{{vehicle.make}} {{vehicle.model}}</strong></div><span class="kfe-state-badge">{{statusLabel(vehicle)}}</span></div><dl class="kfe-detail-list"><div><dt>Acquisition</dt><dd>{{vehicle.acquisition_date}} · {{vehicle.acquisition_type}}</dd></div><div><dt>Acquisition odometer</dt><dd>{{vehicle.acquisition_odometer}} km</dd></div><div><dt>Current odometer</dt><dd>{{vehicle.current_odometer}} km</dd></div><div><dt>Lifetime KM</dt><dd>{{(Number(vehicle.lifecycle_status==='SOLD'?vehicle.sale_odometer:vehicle.lifecycle_status==='RETIRED'?vehicle.retirement_odometer:vehicle.lifecycle_status==='TRANSFERRED'?vehicle.transfer_odometer:vehicle.current_odometer)-Number(vehicle.acquisition_odometer))}} km</dd></div><div><dt>Current drivers</dt><dd>{{driversFor(vehicle).length ? driversFor(vehicle).length : 'None'}}</dd></div></dl><div class="kfe-form-actions"><button class="kfe-secondary-action" type="button" @click="startEdit(vehicle)">Edit</button><button v-if="vehicle.lifecycle_status==='ACTIVE'" class="kfe-secondary-action" type="button" @click="startRetire(vehicle)">Retire</button><button v-if="vehicle.lifecycle_status==='ACTIVE'||vehicle.lifecycle_status==='RETIRED'" class="kfe-secondary-action" type="button" @click="startSell(vehicle)">Sell</button><button class="kfe-list-action" type="button" @click="emit('open','Driver')">Drivers ›</button></div></article><p v-if="!vehicleList.length" class="kfe-boundary-note">No vehicles recorded yet.</p></section>
</section>
</template>
